version: "3"
services:
    app:
        build:
            context: ./
        environment:
            DB_HOST: database
        networks:
            - voyage
        ports:
            - "8002:80"
        volumes:
            - ./:/app

    database:
        image: voyageapp/postgres:14.2
        ports:
            - "54325:5432"
        networks:
            - voyage
networks:
    voyage:
        driver: bridge
