services:
  app:
    context: ./
    primary: true
    exposePort: 80
    environment:
      - name: APP_ENV
        value: voyage
      - name: APP_URL
        value: "https://${VOYAGE_SERVICE_APP_URL}"
  database:
    image: voyageapp/postgres:14.2
